-- =============================================================================
-- refresh_all_marts.sql
-- Пересчитывает все витрины данных в правильном порядке.
--
-- ВАЖНО: этот файл НЕ запускается напрямую через \i из psql или Python.
-- Вместо этого используйте Python-скрипт refresh_all_marts.py (см. ниже),
-- который читает и исполняет каждый файл через psycopg2.
--
-- Если всё же нужен запуск через psql (например, из bash):
--   psql -d bookstore_ods -f sql/marts/refresh_all_marts.sql
--
-- Порядок важен: mart_daily_pulse и mart_plan_fact зависят от актуальных
-- данных в fact_sales, поэтому они идут в начале списка оперативных витрин.
-- =============================================================================

-- Запускается через refresh_all_marts.py, порядок файлов:
--
--   1. sql/marts/01_mart_daily_pulse.sql
--   2. sql/marts/02_mart_plan_fact.sql
--   3. sql/marts/03_mart_inventory_alerts.sql
--   4. sql/marts/04_mart_sales_trends.sql
--   5. sql/marts/05_mart_abc.sql
--   6. sql/marts/06_mart_margin.sql
--   7. sql/marts/07_mart_subscriptions.sql
--
-- Для ручного запуска через psql раскомментируйте строки ниже:
--
-- \i sql/marts/01_mart_daily_pulse.sql
-- \i sql/marts/02_mart_plan_fact.sql
-- \i sql/marts/03_mart_inventory_alerts.sql
-- \i sql/marts/04_mart_sales_trends.sql
-- \i sql/marts/05_mart_abc.sql
-- \i sql/marts/06_mart_margin.sql
-- \i sql/marts/07_mart_subscriptions.sql